### ISSUE TITLE
Please publish new release

### ISSUE THREAD

**Issue by silvioprog** [erlepereira/x11-rs#106]
Hi.

It would be nice to publish a new release of `x11-rs` at Crates. One of the reasons is, for example, the record `_XkbStateRec` available at Crates don't contains any fields, but the Git version declares all fields (`group`, `locked_mods`, `compat_state` etc.).

Thank you!

**Comment by erlepereira** [comment]
My bad. New release published. It now has the _XkbStateRec included (#104)

**Comment by silvioprog** [comment]
Awesome! 🎉
