### ISSUE TITLE
x11 vs x11-dl?

### ISSUE THREAD

**Issue by fzyzcjy** [erlepereira/x11-rs#119]
Hi thanks for the lib! I wonder the difference between these two crates? I have read their doc and crate, but do not find anything to describe it.

**Comment by fzyzcjy** [comment]
Looks like `dl` is the dynamically linked version (just a guess from the source code).

**Comment by El-Wumbus** [comment]
Thank You. I wouldn't have ever known what it meant because the author neglected to type the words in the crate description.

**Comment by AltF02** [comment]
@El-Wumbus you're right, when I inherited this project there was already a lack of documentation. I have created https://github.com/AltF02/x11-rs/issues/171
