### ISSUE TITLE
Include LICENSE files

### ISSUE THREAD

**Issue by ignatenkobrain** [erlepereira/x11-rs#97]
Please include LICENSE text into the repo and all crates. Thanks!

**Comment by erlepereira** [comment]
reference for related discussion #82

**Comment by erlepereira** [comment]
These versions were published with the license fixed as per earlier discussions.
x11-dl    v2.18.5
x11        v2.18.2

**Comment by cuviper** [comment]
`LICENSE-MIT` is in the repo now, but it is not included in the published crates. You can also get a local preview of this by running `cargo package --list`. One easy way to include the license file is to symlink it into each crate's own root.

**Comment by erlepereira** [comment]
Will update this in the next release. Should be quicker than the last release, working on some fixes, cleanups etc.

Thanks.
